Repository laminas/laminas-mvc-skeleton, pull requests merged in 2024-10, with the labels that each got.

#87 Bump minimum versions of optional dependencies during installation
  composer.json
  module/Application/view/layout/layout.phtml
Labels: Enhancement

#88 Fix docker compose command in CI
  .github/workflows/docker-build.yml
Labels: Bug

#89 Readme Linting Fixes
  README.md
Labels: Bug, Documentation
